Repository DND-PickMe/pickme-back, pull requests merged in 2020-02, with the labels that each got.

#22 Add Enterprise CRUD #20
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Enterprise.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/properties/AppProperties.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/EnterpriseRepository.java
  pickmebackend/module-common/src/main/resources/application.yml
  pickmebackend/module-common/src/test/java/com/pickmebackend/properties/AppPropertiesTest.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/main/resources/application.yml
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
Labels: Add, Refactoring, Test

#24 Mapping user
  pickmebackend/module-api/src/main/java/com/pickmebackend/error/ErrorMessageConstant.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/ExperienceService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/LicenseService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/PrizeService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/ProjectService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/SelfInterviewService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Experience.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/License.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Prize.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Project.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/SelfInterview.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/AccountDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/impl/UserDetailsImpl.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/properties/AppProperties.java
  pickmebackend/module-common/src/main/resources/application.yml
  pickmebackend/module-common/src/test/java/com/pickmebackend/properties/AppPropertiesTest.java
  pickmebackend/module-web/build.gradle
  pickmebackend/module-web/src/main/java/com/pickmebackend/annotation/CurrentUser.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ExperienceController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LicenseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/PrizeController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ProjectController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/SelfInterviewController.java
  pickmebackend/module-web/src/main/resources/application.yml
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LicenseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/SelfInterviewControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
Labels: Add, Refactoring, Test

#25 Readme 수정
  README.md
  pickmebackend/README.md
Labels: Docs

#26 Bug Test
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LicenseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/SelfInterviewControllerTest.java
Labels: Bug, Test

#28 이미지 처리
  pickmebackend/module-api/build.gradle
  pickmebackend/module-api/src/main/java/com/pickmebackend/error/ErrorMessageConstant.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/exception/AccountImageException.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountImageService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/SelfInterviewService.java
  pickmebackend/module-api/src/main/resources/application.yml
  pickmebackend/module-common/build.gradle
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/jwt/JwtProvider.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/SelfInterview.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/properties/AccountImageProperties.java
  pickmebackend/module-common/src/main/resources/application.yml
  pickmebackend/module-common/src/test/java/com/pickmebackend/properties/AccountImagePropertiesTest.java
  pickmebackend/module-web/build.gradle
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountImageController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/SelfInterviewController.java
  pickmebackend/module-web/src/main/resources/application.yml
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountImageControllerTest.java
  pickmebackend/pickme-images/default_user.png
Labels: Add

#30 Add CORS Setting
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/SelfInterviewService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
Labels: Add

#31 Add Enterprise Login
  .idea/encodings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/pickme-back.iml
  .idea/vcs.xml
  .idea/workspace.xml
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountImageService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/ExperienceService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/LoginService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/SelfInterviewService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/jwt/JwtFilter.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/jwt/JwtProvider.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Enterprise.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/SelfInterview.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/AccountDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/LoginDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/enums/UserRole.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/impl/UserDetailsImpl.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/properties/AccountImageProperties.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/properties/JwtConstants.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/EnterpriseRepository.java
  pickmebackend/module-common/src/test/java/com/pickmebackend/properties/AccountImagePropertiesTest.java
  pickmebackend/module-common/src/test/java/com/pickmebackend/properties/JwtConstantsTest.java
  pickmebackend/module-web/pickme-images/e4a2964b-5bbd-4535-a89b-c2167fca0997_mugon.png
  pickmebackend/module-web/src/main/java/com/pickmebackend/annotation/CurrentUser.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountImageController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LoginController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountImageControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LicenseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LoginControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/SelfInterviewControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
Labels: Add, Convention, Fix

#32 Wontfix .idea 삭제
  .idea/encodings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/pickme-back.iml
  .idea/vcs.xml
  .idea/workspace.xml
  pickmebackend/.gitignore
Labels: Wontfix

#34 Add Method Authority 설정
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/impl/UserDetailsImpl.java
  pickmebackend/module-web/pickme-images/336ecb49-07a2-4ae2-af6e-1ce42ffea160_mugon.png
  pickmebackend/module-web/pickme-images/539394c4-3758-4148-b5ea-71d2d43a6b65_mugon.png
  pickmebackend/module-web/pickme-images/86990048-88f3-4d38-90c7-8c2f5edea74e_mugon.png
  pickmebackend/module-web/pickme-images/a2d10807-6993-4f3a-880c-cb927fcb56d1_mugon.png
  pickmebackend/module-web/pickme-images/b234c65a-9532-44c2-b0a6-4254842ff0f4_mugon.png
  pickmebackend/module-web/pickme-images/eca59d96-4a5c-4a7b-9b37-65d585bcf6ba_mugon.png
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LicenseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LoginControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/SelfInterviewControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
Labels: Add, Convention, Invalid, Test

#36 빌드 에러 수정
  pickmebackend/build.gradle
  pickmebackend/module-api/build.gradle
  pickmebackend/module-api/src/main/resources/application.yml
  pickmebackend/module-common/build.gradle
  pickmebackend/module-common/src/main/resources/application.yml
  pickmebackend/module-web/build.gradle
  pickmebackend/module-web/pickme-images/336ecb49-07a2-4ae2-af6e-1ce42ffea160_mugon.png
  pickmebackend/module-web/pickme-images/539394c4-3758-4148-b5ea-71d2d43a6b65_mugon.png
  pickmebackend/module-web/pickme-images/86990048-88f3-4d38-90c7-8c2f5edea74e_mugon.png
  pickmebackend/module-web/pickme-images/a2d10807-6993-4f3a-880c-cb927fcb56d1_mugon.png
  pickmebackend/module-web/pickme-images/b234c65a-9532-44c2-b0a6-4254842ff0f4_mugon.png
  pickmebackend/module-web/pickme-images/e4a2964b-5bbd-4535-a89b-c2167fca0997_mugon.png
  pickmebackend/module-web/pickme-images/eca59d96-4a5c-4a7b-9b37-65d585bcf6ba_mugon.png
  pickmebackend/module-web/src/main/resources/application.yml
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountImageControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
Labels: Fix

#37 Refactoring gradle
  pickmebackend/build.gradle
  pickmebackend/module-common/build.gradle
  pickmebackend/module-common/src/main/java/com/pickmebackend/properties/JwtConstants.java
  pickmebackend/module-common/src/test/java/com/pickmebackend/properties/JwtConstantsTest.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/IndexController.java
  pickmebackend/module-web/src/main/resources/application.yml
Labels: Refactoring

#39 스크립트 파일 생성
  pickmebackend/scripts/deploy.sh
Labels: Add

#40 Refactoring 스크립트 파일
  pickmebackend/scripts/deploy.sh
Labels: Refactoring

#41 Refactoring build.gradle
  pickmebackend/build.gradle
Labels: Refactoring

#42 Refactoring securityconfig
  pickmebackend/module-api/src/main/resources/application.yml
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/resources/application.yml
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/IndexController.java
Labels: Refactoring

#43 Add dependency to build.gradle
  pickmebackend/build.gradle
Labels: Add

#44 Refactoring IndexController
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/IndexController.java
Labels: Refactoring

#48 좋아요 기능 구현
  pickmebackend/build.gradle
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-common/build.gradle
  pickmebackend/module-common/src/main/java/com/pickmebackend/DummyData.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountListResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountResponseDto.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
Labels: Add, Test

#46 Add ResponseDto #45
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/ExperienceService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/LicenseService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/LoginService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/PrizeService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/ProjectService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/SelfInterviewService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/enterprise/EnterpriseRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/enterprise/EnterpriseResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/experience/ExperienceRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/experience/ExperienceResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/license/LicenseRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/license/LicenseResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/login/LoginRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/prize/PrizeRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/prize/PrizeResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/project/ProjectRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/project/ProjectResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/selfInterview/SelfInterviewRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/selfInterview/SelfInterviewResponseDto.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ExperienceController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LicenseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LoginController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/PrizeController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ProjectController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/SelfInterviewController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountImageControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LicenseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LoginControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/SelfInterviewControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
  pickmebackend/pickme-images/72be0669-c59d-43dc-b06d-3e23f9a6e5c0_test.png
Labels: Add, Refactoring, Test

#50 Add HATEOAS
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/LoginService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/jwt/Jwt.java
  pickmebackend/module-common/src/test/java/com/pickmebackend/properties/JwtConstantsTest.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LoginController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/resource/ErrorsResource.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LoginControllerTest.java
  pickmebackend/pickme-images/81a658cb-e1db-4bb1-afc9-e0a721ec4f20_test.png
  pickmebackend/pickme-images/a6c6d7f6-5381-44e7-ba94-867f7eeb542f_test.png
  pickmebackend/pickme-images/c669410e-c744-4957-bdef-d7124001f28d_test.png
  pickmebackend/pickme-images/c86ad120-8eda-4c3c-85ed-a227c052c821_test.png
Labels: Add, Test

#52 Add RestDocs #51
  pickmebackend/module-api/build.gradle
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/ExperienceService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/LicenseService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/LoginService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/PrizeService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/ProjectService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/SelfInterviewService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/login/JwtResponseDto.java
  pickmebackend/module-common/src/test/java/com/pickmebackend/properties/JwtResponseDtoConstantsTest.java
  pickmebackend/module-web/build.gradle
  pickmebackend/module-web/src/docs/asciidoc/index.adoc
  pickmebackend/module-web/src/main/asciidoc/index.adoc
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ExperienceController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/IndexController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LicenseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LoginController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/PrizeController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ProjectController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/SelfInterviewController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/resource/LoginResource.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/IndexControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LicenseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LoginControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/SelfInterviewControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/RestDocsConfiguration.java
  pickmebackend/pickme-images/099d3592-667e-490a-8c88-22093fe8866d_test.png
  pickmebackend/pickme-images/0d78efaf-07d7-4294-b543-8242e4676935_test.png
  pickmebackend/pickme-images/1da6f48d-d86b-4b13-a1cf-b4b822491af6_test.png
  pickmebackend/pickme-images/298c26fc-9947-44b8-82a2-74b3445d2264_test.png
  pickmebackend/pickme-images/9c370a32-539f-4a7f-aa05-a88e7d666b53_test.png
  pickmebackend/pickme-images/a11395f3-40fc-4add-b381-b3df50f95b1b_test.png
  pickmebackend/pickme-images/b1967857-f420-489b-9d2c-1eedc2ae6e29_test.png
  pickmebackend/pickme-images/d6f2b8b1-2d9e-4c93-89b7-dc7dbcdf6c93_test.png
  pickmebackend/pickme-images/df75106b-8be2-4d08-8e39-c86f2e6dc884_test.png
  pickmebackend/pickme-images/f1054026-0145-4090-aeb4-3e7062dff13c_test.png
Labels: Add, Docs, Test

#54 RestDocs 접근 권한 수정
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/pickme-images/099d3592-667e-490a-8c88-22093fe8866d_test.png
  pickmebackend/pickme-images/0d78efaf-07d7-4294-b543-8242e4676935_test.png
  pickmebackend/pickme-images/1da6f48d-d86b-4b13-a1cf-b4b822491af6_test.png
  pickmebackend/pickme-images/298c26fc-9947-44b8-82a2-74b3445d2264_test.png
  pickmebackend/pickme-images/72be0669-c59d-43dc-b06d-3e23f9a6e5c0_test.png
  pickmebackend/pickme-images/81a658cb-e1db-4bb1-afc9-e0a721ec4f20_test.png
  pickmebackend/pickme-images/820b0fac-9adf-47ef-b22c-d223b5eaea11_test.png
  pickmebackend/pickme-images/9c370a32-539f-4a7f-aa05-a88e7d666b53_test.png
  pickmebackend/pickme-images/a11395f3-40fc-4add-b381-b3df50f95b1b_test.png
  pickmebackend/pickme-images/b1967857-f420-489b-9d2c-1eedc2ae6e29_test.png
  pickmebackend/pickme-images/c669410e-c744-4957-bdef-d7124001f28d_test.png
  pickmebackend/pickme-images/c7aee292-eb66-4d8d-85e4-289e3aa65541_test.png
  pickmebackend/pickme-images/d6f2b8b1-2d9e-4c93-89b7-dc7dbcdf6c93_test.png
  pickmebackend/pickme-images/df75106b-8be2-4d08-8e39-c86f2e6dc884_test.png
  pickmebackend/pickme-images/f1054026-0145-4090-aeb4-3e7062dff13c_test.png
Labels: Fix

#56 Add Load AllAccounts #55
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/AccountRepository.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
  pickmebackend/pickme-images/477b6651-c8af-450f-bdbf-92230413806c_test.png
  pickmebackend/pickme-images/b7a9adef-c877-4ae9-ad83-bd5c590444e8_test.png
  pickmebackend/pickme-images/c41cc879-10e5-4777-b3ae-c53a03d8053d_test.png
Labels: Add, Test

#57 technology 필드 삭제
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountResponseDto.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountImageControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LicenseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/SelfInterviewControllerTest.java
  pickmebackend/pickme-images/1faa6639-13fa-415b-988e-5c5edf5de365_test.png
  pickmebackend/pickme-images/6a66003a-98fe-4724-90d8-496bb900dea1_test.png
  pickmebackend/pickme-images/76e74185-ab95-4733-a498-db49ff80a491_test.png
  pickmebackend/pickme-images/7c7364fd-6ea6-4140-b517-6e2879ed2044_test.png
Labels: Bug, Fix

#59 Exp position
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/SkillService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/AccountTech.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Technology.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/AccountTechRepository.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/TechnologyRepository.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/SkillController.java
  pickmebackend/module-web/src/main/resources/application.yml
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LicenseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/SelfInterviewControllerTest.java
  pickmebackend/pickme-images/1faa6639-13fa-415b-988e-5c5edf5de365_test.png
  pickmebackend/pickme-images/477b6651-c8af-450f-bdbf-92230413806c_test.png
  pickmebackend/pickme-images/6a66003a-98fe-4724-90d8-496bb900dea1_test.png
  pickmebackend/pickme-images/76e74185-ab95-4733-a498-db49ff80a491_test.png
  pickmebackend/pickme-images/7c7364fd-6ea6-4140-b517-6e2879ed2044_test.png
  pickmebackend/pickme-images/b7a9adef-c877-4ae9-ad83-bd5c590444e8_test.png
  pickmebackend/pickme-images/c41cc879-10e5-4777-b3ae-c53a03d8053d_test.png
Labels: Add

#61 변수 이름 수정
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountResponseDto.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
Labels: Refactoring

#62 yml 수정
  pickmebackend/module-web/src/main/resources/application.yml
Labels: Bug, Fix

#63 yml 수정
  pickmebackend/module-web/src/main/resources/application.yml
Labels: Bug, Fix

#64 Add Load Account
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountImageService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/AccountTech.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Technology.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/properties/JwtConstants.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/AccountRepository.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/AccountTechRepository.java
  pickmebackend/module-common/src/test/java/com/pickmebackend/properties/AccountImagePropertiesTest.java
  pickmebackend/module-web/src/docs/asciidoc/index.adoc
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LoginController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/SelfInterviewController.java
  pickmebackend/module-web/src/main/resources/application.yml
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountImageControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LoginControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
  pickmebackend/pickme-images/05886f1c-b5cb-4d59-8979-625751e27054_test.png
  pickmebackend/pickme-images/6aa34117-ed2f-4a65-9844-1f20b1b4e1cd_test.png
  pickmebackend/pickme-images/6e728919-adff-4c39-b541-44454f48a961_test.png
  pickmebackend/pickme-images/f3e67e0d-d659-4396-a9c7-afaadfa07c15_test.png
Labels: Add, Fix, Test

#66 Add Fields At Account #65
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountResponseDto.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
Labels: Add, Test

#69 Add 좋아요 정렬
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/SkillService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/DummyData.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/AccountRepository.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/SkillController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
Labels: Add

#71 Add Load Enterprise
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/enterprise/EnterpriseResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/EnterpriseRepository.java
  pickmebackend/module-web/src/docs/asciidoc/index.adoc
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LoginController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LoginControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
  pickmebackend/pickme-images/02f577f9-7e12-4bab-973e-7a85bc23e3f3_test.png
  pickmebackend/pickme-images/6aa34117-ed2f-4a65-9844-1f20b1b4e1cd_test.png
  pickmebackend/pickme-images/6e728919-adff-4c39-b541-44454f48a961_test.png
  pickmebackend/pickme-images/default_user.png
  pickmebackend/pickme-images/f3e67e0d-d659-4396-a9c7-afaadfa07c15_test.png
Labels: Add, Test

#70 유저 수정 시 비밀번호 필드 삭제
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountInitialRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountRequestDto.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountImageControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LoginControllerTest.java
  pickmebackend/pickme-images/59a5c610-4516-4137-8ce7-6071f46218cd_test.png
Labels: Convention, Refactoring

#73 유저 필드 추가
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/AccountRepository.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/SkillController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
Labels: Add, Bug, Fix, Test

#75 Bug positions #74
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
Labels: Bug, Fix

#78 에러 메시지 반환 포맷 수정
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountImageService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/common/ErrorsFormatter.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ExperienceController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LicenseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LoginController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/PrizeController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ProjectController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/SelfInterviewController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountImageControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LicenseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LoginControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/SelfInterviewControllerTest.java
Labels: Refactoring, Test

#79 Refactoring Error Message 수정, 조회수 에러 수정
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountInitialRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/enterprise/EnterpriseRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/login/LoginRequestDto.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
Labels: Bug, Refactoring
