Repository DND-PickMe/pickme-back, pull requests merged in 2020-03, with the labels that each got.

#80 Add Filtering
  pickmebackend/.gitignore
  pickmebackend/build.gradle
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountImageService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/common/ErrorsFormatter.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/BeanConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountFilteringRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/impl/UserDetailsServiceImpl.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/EnterpriseRepository.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/account/AccountRepository.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/account/AccountRepositoryCustom.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/account/AccountRepositoryImpl.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/account/AccountTechRepository.java
  pickmebackend/module-web/src/docs/asciidoc/index.adoc
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/main/resources/application.yml
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountImageControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LicenseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LoginControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/SelfInterviewControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
  pickmebackend/pickme-images/59a5c610-4516-4137-8ce7-6071f46218cd_test.png
Labels: Add, Docs, Fix, Test

#82 Fix HATEOAS #81
  pickmebackend/.gitignore
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/ExperienceService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/LicenseService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/PrizeService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/ProjectService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/SelfInterviewService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/account/AccountRepositoryImpl.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ExperienceControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LicenseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/PrizeControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/ProjectControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/SelfInterviewControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
Labels: Fix

#85 Add FavoriteFlag 필드 생성
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountFavoriteFlagResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/account/AccountRepositoryImpl.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/resource/AccountFavoriteFlagResource.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/resource/AccountResource.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
Labels: Add

#86 Fix filtering #83
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountFilteringRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/account/AccountRepositoryImpl.java
  pickmebackend/module-web/src/docs/asciidoc/index.adoc
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ExperienceController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/IndexController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LicenseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LoginController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/PrizeController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ProjectController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/SelfInterviewController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
Labels: Docs, Fix, Test

#88 Fix Filtering #87
  pickmebackend/build.gradle
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/enterprise/EnterpriseFilterRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/EnterpriseRepository.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/account/AccountRepository.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/account/AccountRepositoryImpl.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/enterprise/EnterpriseRepository.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/enterprise/EnterpriseRepositoryCustom.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/enterprise/EnterpriseRepositoryImpl.java
  pickmebackend/module-web/src/docs/asciidoc/index.adoc
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/main/resources/application.yml
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
Labels: Docs, Fix, Test

#90 채용 제안
  dummy-data/add_tag.py
  dummy-data/sign_up_acc.py
  dummy-data/sign_up_enter.py
  dummy-data/sign_up_normal.py
  images/handshake.jpg
  images/logo.png
  pickmebackend/.gitignore
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-api/src/main/resources/application.yml
  pickmebackend/module-api/src/main/resources/templates/html/email.html
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/enterprise/EnterpriseSuggestionRequestDto.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/main/resources/application.yml
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
Labels: Add

#92 Fix SendEmail
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-api/src/main/resources/templates/html/email.html
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/enterprise/SuggestionDto.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
Labels: Add, Bug

#93 Fix yml
  pickmebackend/module-web/src/main/resources/application.yml
Labels: Fix

#96 Bug 좋아요 버그 수정 #95
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
Labels: Bug, Fix

#97 Add technologies sort
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/Account.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountFavoriteFlagResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/account/AccountResponseDto.java
Labels: Add

#98 Add VerificationCode #94
  pickmebackend/.gitignore
  pickmebackend/module-api/src/main/java/com/pickmebackend/error/ErrorMessageConstant.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-api/src/main/resources/application.yml
  pickmebackend/module-api/src/main/resources/templates/html/code.html
  pickmebackend/module-common/src/main/java/com/pickmebackend/config/SecurityConfig.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/VerificationCode.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/verificationCode/SendCodeRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/verificationCode/SendCodeResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/verificationCode/VerifyCodeRequestDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/domain/dto/verificationCode/VerifyCodeResponseDto.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/repository/VerificationCodeRepository.java
  pickmebackend/module-common/src/main/resources/application.yml
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/resources/application.yml
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/AccountImageControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/EnterpriseControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/LoginControllerTest.java
  pickmebackend/module-web/src/test/java/com/pickmebackend/controller/common/BaseControllerTest.java
Labels: Add, Fix, Test

#102 코드 리팩토링
  README.md
  pickmebackend/module-api/src/main/java/com/pickmebackend/exception/CodeNotExist.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/exception/UserNotFoundException.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountImageService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/AccountService.java
  pickmebackend/module-api/src/main/java/com/pickmebackend/service/EnterpriseService.java
  pickmebackend/module-common/src/main/java/com/pickmebackend/properties/RestDocsConstants.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/annotation/account/AccountAspect.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/AccountImageController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/EnterpriseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ErrorController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ExperienceController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/IndexController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LicenseController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/LoginController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/PrizeController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/ProjectController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/controller/SelfInterviewController.java
  pickmebackend/module-web/src/main/java/com/pickmebackend/resource/HateoasFormatter.java
Labels: Refactoring
